version: '3.7'

services:
  nominal-account-api:
    image: nominal-account-api
    env_file:
      - ./docker/api/.env
    volumes:
      - ./:/app:cached
    ports:
      - 4005:4005
    working_dir: /application/build
    command: node main.js

volumes:
  pg_data:
